#markdown: rdiscount
pygments: true
permalink: /posts/:title
auto: true
#rdiscount:
  #extensions: [smart]

name: Ory Band
url: http://OryBand.com
description: Social guitar-player on wheels.
twitter: OryBand
github: oryband
gravatar_url: http://www.gravatar.com/avatar/1f10c2fce594fe4d5bc05b6e5f466e6a.png
